version: '3.5'

services:
  # This target can be split onto three to have finer-grained CI pipelines with increasing order of complexity:
  # - Build
  # - Unit Test
  # - Integration Test
  # - Acceptance Test
  tests:
    build:
      context: .
      target: BUILD_IMAGE
    env_file:
      - environment.docker.env
    command: dockerize
              -wait tcp://postgres:5432
              -timeout 5m -wait-retry-interval 2s
        sh -c '/app/gradlew test integrationTest acceptanceTest'
    depends_on:
      - postgres

  run:
    build:
      context: .
      target: PRD_IMAGE
    image: bphenriques/employee-shift-api
    env_file:
      - environment.docker.env
    command: java -XX:+UseG1GC -XX:+CrashOnOutOfMemoryError -Xmx512m -Xms512m -jar employee-shift-api.jar
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2
