spring.profiles.active: dev
spring.application.name: employee-shift-api
logging.level.com.bphenriques: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  flyway:
    locations: filesystem:../db/migration

---

management:
  server.port: 8081
  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: readinessState,diskSpace
        liveness.include: livenessState,ping
      enabled: true
      show-details: ALWAYS
      show-components: ALWAYS
    prometheus.enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include:
      - health
      - prometheus

  metrics:
    # instrumentation of requests handled by Spring MVC
    web.server.request.autotime.enabled: true
    distribution.percentiles-histogram.http:
      server.requests: true
      client.requests: true
