spring.profiles.active: test
spring.application.name: employee-shift-api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  flyway:
    locations: filesystem:../db/migration
