# This file will potentially have secrets and will vary per environment!
# Therefore, this should leverage a Secret storage service.
# Food for thought: https://medium.com/@harsh.manvar111/kubernetes-secret-vs-vault-fb57d75ce553

apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-shifts-api-config
  namespace: default
  labels:
    app: employee-shifts-api
data:
  LOGGING_LEVEL_COM_BPHENRIQUES: INFO
  SPRING_PROFILES_ACTIVE: stg
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: postgresadmin
  SPRING_DATASOURCE_PASSWORD: admin123
  SPRING_FLYWAY_LOCATIONS: filesystem:/app/db/migration
