spring.profiles.active: dev
spring.application.name: employee-shift-api

spring.flyway.baselineOnMigrate: true

---

management:
  server.port: 8081
  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: readinessState,diskSpace,r2dbc
        liveness.include: livenessState,ping
      enabled: true
      show-details: ALWAYS
      show-components: ALWAYS
    prometheus.enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include:
      - health
      - prometheus
