spring.profiles.active: dev
spring.application.name: employee-shift-api

# Flyway is not yet fully compatible with R2DBC.
# See: https://stackoverflow.com/questions/59553647/how-to-run-flyway-migration-for-reactive-r2dbc-driver-on-sprintboot-stratup
spring:
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baselineOnMigrate: true

---

management:
  server.port: 8081
  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: readinessState,diskSpace,r2dbc
        liveness.include: livenessState,ping
      enabled: true
      show-details: ALWAYS
      show-components: ALWAYS
    prometheus.enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include:
      - health
      - prometheus

  metrics:
    # instrumentation of requests handled by Spring MVC
    web.server.request.autotime.enabled: true
    distribution.percentiles-histogram.http:
      server.requests: true
      client.requests: true
